version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    networks:
      - mynetwork

  backend:
    image: portfolio-opt-backend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
